config/routes.rb
MobilecloudhqCore::Application.routes.draw do

  resources :websites
  resources :dashboard
  resources :website_feed_entries

  root :to => "website_feed_entries#index"

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include MongoidExt::Storage

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %w[owner user moderator admin]

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  index :email
  field :encrypted_password, :type => String, :default => ""

  field :name,                :type => String, :limit => 100
  field :role,                :type => String, :default => "user"
  field :website_ids,         :type => Array, :default => []

  validates_presence_of :email
  validates_presence_of :encrypted_password
  validates_inclusion_of :role, :in => ROLES

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

end

app/models/website.rb
class Website

  attr_accessor :id, :name, :domain, :subdomain, :status, :website_feed_url

  def initialize(attribute)
    self.id = attribute['id']
    self.domain = attribute['domain']
    self.subdomain = attribute['subdomain']
    self.status = attribute['status']
    self.website_feed_url = attribute['website_feed_url']
  end

  def self.get_website_by_params(params = {})
    response = WebsiteService.get_website_by_params(params)
    if response.code == 200
      body = response.body
      json_body = JSON.parse(body)
      self.init_object(json_body)
      @collections
    end
  end

  protected

  def self.init_object(json_body)
    @collections = []
    if json_body['objects'].present?
      json_body['objects'].each do |attribute|
        @collections.push(new attribute)
      end
    end
  end


end

app/models/website_feed_entry.rb
class WebsiteFeedEntry

  attr_accessor :id, :url, :title, :summary, :author, :content

  def initialize(attribute)
    self.id = attribute['id']
    self.url = attribute['url']
    self.title = attribute['title']
    self.author = attribute['author']
    self.summary = attribute['summary']
    self.content = attribute['content']
  end

  def self.get_all_entries(website)
      return [] unless website.present?
      response = WebsiteFeedEntryService.get_website_feed_by_params({"website_id" => website.id.to_s})
      if response.code == 200
        body = response.body
        body_arr = JSON.parse(body)
        self.init_object(body_arr)
        @collections
      end
  end

  def self.get_website_feed_entry(id)
    return [] unless id.present?
    response = WebsiteFeedEntryService.get_website_feed_by_id(id)
    if response.code == 200
      body = response.body
      body_arr = JSON.parse(body)
      new body_arr
    end
  end

  protected

  def self.init_object(json_body)
    @collections = []
    if json_body['objects'].present?
      json_body['objects'].each do |attribute|
        @collections.push(new attribute)
      end
    end
  end

end

app/models/website_feed_entry_service.rb
class WebsiteFeedEntryService

  def self.get_website_feed_by_params(params = {})
    response = Typhoeus::Request.get("#{App_Config.api_end_point}/website_feed_entries", :params => params)
  end

  def self.get_website_feed_by_id(id = 0)
    response = Typhoeus::Request.get("#{App_Config.api_end_point}/website_feed_entries/#{id}/")
  end

end

app/models/website_service.rb
class WebsiteService

  def self.get_website_by_params(params = {})
    response = Typhoeus::Request.get("#{App_Config.api_end_point}/websites", :params => params)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include Subdomains

  before_filter :find_website

  layout :set_layout
  protected

  def set_layout
     if env && env["HTTP_X_PJAX"].present? && !params[:_refresh]
       nil
     elsif devise_controller? || (action_name == "new" && controller_name == "users")
       'sessions'
     elsif current_website['current_theme'].present?
       current_website['current_theme']
     else
       'application'
     end
  end

  def current_website
    @current_website
  end
  def find_website
    return if App_Config.app_domain == request.host
    @current_website ||= begin
      subdomains = request.subdomains
      subdomains.delete("www") if request.host == "www.#{App_Config.app_domain}"
      website_document = Website.get_website_by_params({"domain" => request.host, "status" => "active"})
      unless website_document
        if subdomain = subdomains.first
          website_document = Website.get_website_by_params({"status" => "active", "subdomain" => subdomain})
          unless website_document.nil?
            redirect_to domain_url(:custom => website_document.first.domain)
            return
          end
        end
      end
      website_document.first
    end
    @current_website

    unless website_document.present?
      flash.now[:notice] = "Website not found"
      redirect_to domain_url(:custom => App_Config.app_domain)
      return
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  layout 'application'

  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/website_feed_entries_controller.rb
class WebsiteFeedEntriesController < ApplicationController
  layout 'default'
  before_filter :check_website
  def index
    @website_feed_entries = WebsiteFeedEntry.get_all_entries(current_website)
    respond_to do |format|
      format.html
      format.json { render json: @website_feed_entries }
    end
  end

  def show
    @feed = WebsiteFeedEntry.get_website_feed_entry(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  protected

  def check_website
    redirect_to dashboard_index_url unless current_website
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/dashboard/index.html.erb
<h3>Welcome To Mobile Cloud HQ</h3>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "MobilecloudhqCore" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">MobilecloudhqCore</a>

      <div class="container nav-collapse">
        <ul class="nav">
          <li>
            <ul class="nav nav-pills">
              <li class="dropdown">
                <a class="dropdown-toggle"
                   data-toggle="dropdown"
                   href="#">
                  Manage
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Create Website", new_website_url %></li>
                </ul>
              </li>
            </ul>
          <li><%= link_to "Link2", "/path2" %></li>
          <li><%= link_to "Link2", "/path2" %></li>
          <li><%= link_to "Link3", "/path3" %></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="row">
      <div class="span9">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
              <a class="close" data-dismiss="alert">&#215;</a>
              <div id="flash_#{name}">
                <%= msg.html_safe if msg.is_a?(String) %>
              </div>
            </div>
        <% end %>

        <%= yield %>
      </div>
      <div class="span3">
        <div class="well sidebar-nav">
          <h3>Sidebar</h3>
          <ul class="nav nav-list">
            <li class="nav-header">Sidebar</li>
            <li><%= link_to "Link1", "/path1" %></li>
            <li><%= link_to "Link2", "/path2" %></li>
            <li><%= link_to "Link3", "/path3" %></li>
          </ul>
        </div>
        <!--/.well -->
      </div>
      <!--/span-->
    </div>
    <!--/row-->
  </div>
  <!--/content-->

  <footer>
    <p>&copy; Company 2012</p>
  </footer>

</div>
<!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MobilecloudhqCore" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "default", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

  <div data-role="page">

    <header data-role="header">

    </header>


    <div data-role="content">

      <%= yield %>

    </div>

    <footer data-role="footer">

    </footer>

  </div>

  <!-- Javascripts
 ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "default" %>

  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "MobilecloudhqCore" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">MobilecloudhqCore</a>

      <div class="container nav-collapse">
        <ul class="nav">
          <li>
            <ul class="nav nav-pills">
              <li class="dropdown">
                <a class="dropdown-toggle"
                   data-toggle="dropdown"
                   href="#">
                  Manage
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Create Website", new_website_url %></li>
                </ul>
              </li>
            </ul>
          <li><%= link_to "Link2", "/path2" %></li>
          <li><%= link_to "Link2", "/path2" %></li>
          <li><%= link_to "Link3", "/path3" %></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="row">
      <div class="span9">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
              <a class="close" data-dismiss="alert">&#215;</a>
              <div id="flash_#{name}">
                <%= msg.html_safe if msg.is_a?(String) %>
              </div>
            </div>
        <% end %>

        <%= yield %>
      </div>
      <div class="span3">
        <div class="well sidebar-nav">
          <h3>Sidebar</h3>
          <ul class="nav nav-list">
            <li class="nav-header">Sidebar</li>
            <li><%= link_to "Link1", "/path1" %></li>
            <li><%= link_to "Link2", "/path2" %></li>
            <li><%= link_to "Link3", "/path3" %></li>
          </ul>
        </div>
        <!--/.well -->
      </div>
      <!--/span-->
    </div>
    <!--/row-->
  </div>
  <!--/content-->

  <footer>
    <p>&copy; Company 2012</p>
  </footer>

</div>
<!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/website_feed_entries/index.html.erb
<ul data-role="listview" data-theme="c" data-dividertheme="d" data-counttheme="e">
  <% if @website_feed_entries.present? %>
      <% @website_feed_entries.each do |feed_entry| %>
          <li>
            <h2>
              <%= link_to feed_entry.title, website_feed_entry_path(feed_entry.id.to_s)  %>
              <a href="#">
                <%= feed_entry.title %>
              </a>
            </h2>
          </li>
      <% end %>
  <% end %>
</ul>

app/views/website_feed_entries/show.html.erb
<h1> <%= @feed.title %> </h1>
<div> <%= @feed.summary %> </div>

app/views/websites/_form.html.erb
<%= form_for @website, :html => {:class => 'form-horizontal'} do |f| %>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'input-xlarge', :rows => 3 %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :subdomain, 'Url', :class => 'control-label' %>
      <div class="controls">
        <div class="input-append">
          <%= f.text_field :subdomain, :class => 'span2', :id => 'appendedInput' %>
          <span class="add-on">.mobilecloudhq.com</span>
        </div>
      </div>
    </div>


    <div class="control-group">
      <%= f.label :website_feed_url, 'Website Feed Url', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :website_feed_url, :class => 'text_field' %>
      </div>
    </div>




    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  websites_path, :class => 'btn' %>
    </div>
<% end %>

app/views/websites/edit.html.erb
<%- model_class = Website -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/websites/index.html.erb
<%- model_class = Website -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:subdomain) %></th>
      <th><%= model_class.human_attribute_name(:domain) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.name %></td>
        <td><%= website.subdomain %></td>
        <td><%= website.domain %></td>
        <td><%=l website.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_website_path(website), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      website_path(website),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_website_path,
            :class => 'btn btn-primary' %>

app/views/websites/new.html.erb
<%- model_class = Website -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/websites/show.html.erb
<%- model_class = Website -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @website.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subdomain) %>:</strong></dt>
  <dd><%= @website.subdomain %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              websites_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_website_path(@website), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              website_path(@website),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>